<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            layout([
                {
                    component: 'Magento_PaymentRequestAPI/js/product/pay-now',
                    name: 'payment_request_pay_now'
                }
            ]);
        })
    })
</script>
<div data-bind="scope: 'payment_request_pay_now'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>